name: Meow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.75
  lightness: 0.5845143788028508
  saturation: 0.4870195025578141
  rhythmicContrast: 0.15799247357062995
purpose: []
